export const LANGUAGES = [
    { value: "vo", label: "Original Version" },
    { value: "eng", label: "English" },
    { value: "spa", label: "Spanish" },
    { value: "fre", label: "French" },
    { value: "ger", label: "German" },
    { value: "ita", label: "Italian" },
    { value: "jpn", label: "Japanese" },
    { value: "kor", label: "Korean" },
    { value: "chi", label: "Chinese" },
    { value: "rus", label: "Russian" },
    { value: "por", label: "Portuguese" },
    { value: "ara", label: "Arabic" },
    { value: "hin", label: "Hindi" },
    { value: "dut", label: "Dutch" },
    { value: "swe", label: "Swedish" },
    { value: "nor", label: "Norwegian" },
    { value: "dan", label: "Danish" },
    { value: "fin", label: "Finnish" },
    { value: "pol", label: "Polish" },
    { value: "tur", label: "Turkish" },
    { value: "heb", label: "Hebrew" },
    { value: "gre", label: "Greek" },
    { value: "cze", label: "Czech" },
    { value: "hun", label: "Hungarian" },
    { value: "rum", label: "Romanian" },
    { value: "ukr", label: "Ukrainian" },
    { value: "tha", label: "Thai" },
    { value: "vie", label: "Vietnamese" },
    { value: "ind", label: "Indonesian" },
    { value: "may", label: "Malay" },
];
